# PRACTICA PROFESIONALIZANTE I

## Proyecto: Predicción de grasa corporal

### Docentes: 
* Pérez, Narciso
* Prado, Héctor
* Charletti, Carlos

### Alumnos:
* Ingaramo, Ma. Eugenia - Sala 1
* Lonardi, Pablo - Sala  1
* Margheim, Carolina - Sala 2
* Ontiveros, Manuel -  Sala 1
* Sosa, Rorigo - Sala 2
* Zenere, Mauricio - Sala 2

### Sobre Nosotros:
Somos una innovadora startup dedicada a resolver desafíos complejos de diferentes empresas u organizaciones utilizando para tal fin diferentes herramientas de ciencia de datos. Utilizamos diferentes herramientas de analisis, exploración, visualizacion y predicción de datos.

### Situación:

Un consorcio formado por reconocidos médicos especializados en medicina deportiva, entrenadores personales y nutricionistas de élite nos ha contratado para abordar una problemática crítica Observan una creciente interconexión entre el rendimiento físico y la salud de los deportistas, pero carecen de una herramienta precisa que les permita prever y optimizar ambos aspectos en sus atletas.

### Solución propuesta:

Nuestro objetivo es desarrollar una plataforma innovadora que integre datos clave sobre la salud y el rendimiento físico. Esta plataforma proporcionará predicciones precisas y recomendaciones fundamentadas en datos. Buscamos empoderar a los profesionales del deporte para que tomen decisiones informadas que impulsen el rendimiento y mejoren la salud de los deportistas. Esta colaboración representa un desafío apasionante donde combinaremos nuestro expertise en ciencia de datos con el conocimiento experto de los médicos y entrenadores. Juntos, vamos a revolucionar la forma en que se abordan la salud y el rendimiento en el ámbito deportivo, marcando un hito significativo en la industria.

### Trabajo en el Notebook:
* **Análisis Exploratorio de Datos (EDA):**

Realizaremos un análisis exploratorio de datos exhaustivo. Exploraremos cómo la edad, el género, la altura, el peso y otros factores influyen en el rendimiento físico y la salud de las personas. Este análisis nos ayudará a comprender las relaciones clave entre las variables y nos guiará en la construcción de modelos precisos.

* **Modelado de Machine Learning:**
Utilizaremos avanzadas técnicas de aprendizaje automático para crear un modelo preciso de predicción. Entrenaremos el modelo con el conjunto de datos y evaluaremos su rendimiento. Nuestro objetivo es lograr un modelo que prediga el rendimiento físico y la salud con alta precisión.

### Trabajo en Streamlit:
* **Desarrollo de la Aplicación Web:**
Construiremos una aplicación web interactiva utilizando Streamlit. Esta aplicación permitirá a los profesionales de la salud y los deportistas ingresar información sobre sus pacientes, como edad, género, altura, peso, entre otros. Basándonos en los datos ingresados, nuestro modelo proporcionará predicciones sobre el rendimiento físico y la salud.

* **Facilitando Decisiones Informadas:**
La aplicación proporcionará información y recomendaciones fundamentadas en datos. Esto permitirá a los usuarios tomar decisiones informadas sobre la mejora de la salud y el rendimiento físico de sus pacientes o de ellos mismos. Además, podrán evaluar estrategias para optimizar el rendimiento físico basadas en los resultados de nuestro modelo.

### Modelado:

Una vez obtenido el acceso a la base, se volcó el contenido de la misma a un archivo .csv. El consorcio nos brindó una descripción de las variables presentes en el mismo, como así también el dominio o rango esperado de sus variables numéricas, en caso de que haya algún tipo de error en la base de datos. En una primera etapa se le prestará se le prestará especial atención a aquellas variables que contengan valores considerados absurdos e imposibles para el ser humano.

### Descripción  de variables:

Contexto: El dataset contiene 13.393 registros que ilustran el grado de rendimiento con la edad y algunos datos de performance en el ejercicio distribuidos en las siguientes 12 columnas.

* age (Edad = años): 20 - 64
* gender (Género = Masculino/Femenino): F,M
* height_cm (Altura en centímetros): cm
* weight_kg (Peso en kilogramos)
* body fat_% (Porcentaje de grasa corporal)
* diastolic (Presión arterial diastólica - min)
* systolic (Presión arterial sistólica - min)
* gripForce (Fuerza de agarre)
* sit and bend forward_cm (Sentarse e inclinarse hacia adelante): cm
* sit-ups counts (Cantidad de abdominales)
* broad jump_cm (Salto largo): cm
* class : A,B,C,D ( A: Mejor - D: Peor) / Variable categórica ordinal

### 1-  Dependencies:

In [52]:
### Importar librerías:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### 2-  Data Acquisition:

In [53]:
# Importar dataset  desde github (raw):
url="https://raw.githubusercontent.com/CaroMargh/Grupo1-PP1/main/data/bodyPerformance.csv"
# Leer dataset:
df = pd.read_csv(url)
# Mostrar dataset:
display(df)

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27.0,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25.0,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31.0,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32.0,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28.0,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
13388,25.0,M,172.1,71.80,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21.0,M,179.7,63.90,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39.0,M,177.2,80.50,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64.0,F,146.1,57.70,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34.0,M,164.0,66.10,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

### 3-  Data Understanding:

In [54]:
# Descripción del dataset:

def description (data: pd.DataFrame):
    print(f"Shape: \n{data.shape}\n")
    print(f"Dimension: \n{data.ndim}\n")
    print(f"Data types: \n{data.dtypes}\n")
    print(f"Data information: \n{data.info()}\n")
    print(f"Data description: \n{data.describe()}\n")
    print(f"Total de valores nulos: \n{data.isnull().sum()}\n")
    print(f"Total de valores duplicados: \n{data.duplicated().sum()}\n")

description(df)

Shape:
(13393, 12)

Dimension:
2

Data types:
age                        float64
gender                      object
height_cm                  float64
weight_kg                  float64
body fat_%                 float64
diastolic                  float64
systolic                   float64
gripForce                  float64
sit and bend forward_cm    float64
sit-ups counts             float64
broad jump_cm              float64
class                       object
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      13393 non-null  float64
 1   gender                   13393 non-null  object
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13393 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13393 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object
dtypes: float64(10), object(2)
memory usage: 1.2+ MB
Data information:
None

Data description:
                age     height_cm     weight_kg    body fat_%     diastolic  \
count  13393.000000  13393.000000  13393.000000  13393.000000  13393.000000
mean      36.775106    168.559807     67.447316     23.240165     78.796842
std       13.625639      8.426583     11.949666      7.256844     10.742033
min       21.000000    125.000000     26.300000      3.000000      0.000000
25%       25.000000    162.400000     58.200000     18.000000     71.000000
50%       32.000000    169.200000     67.400000     22.800000     79.000000
75%       48.000000    174.800000     75.300000     28.000000     86.000000
max       64.000000    193.800000    138.100000     78.400000    156.200000

           systolic     gripForce  sit and bend forward_cm  sit-ups counts  \
count  13393.000000  13393.000000             13393.000000    13393.000000
mean     130.234817     36.963877                15.209268       39.771224
std       14.713954     10.624864                 8.456677       14.276698
min        0.000000      0.000000               -25.000000        0.000000
25%      120.000000     27.500000                10.900000       30.000000
50%      130.000000     37.900000                16.200000       41.000000
75%      141.000000     45.200000                20.700000       50.000000
max      201.000000     70.500000               213.000000       80.000000

       broad jump_cm
count   13393.000000
mean      190.129627
std        39.868000
min         0.000000
25%       162.000000
50%       193.000000
75%       221.000000
max       303.000000

Total de valores nulos:
age                        0
gender                     0
height_cm                  0
weight_kg                  0
body fat_%                 0
diastolic                  0
systolic                   0
gripForce                  0
sit and bend forward_cm    0
sit-ups counts             0
broad jump_cm              0
class                      0
dtype: int64

Total de valores duplicados:
1

#### Observaciones:

* Se podrían realizar la conversión de altura de cm a m.
* La columna de genero y la de clase se convertirán a formato de datos categóricos usando get_dummies.
* Sería util pasar las columnas en centímetros a metros para unificar criterios y luego borrar las columnas en cm.
* Es útil cambiar el nombre de las columnas para el entendimiento de todo el equipo que habla español
* Con los valores otorgados se podría calcular el IMC (Índice de Masa Corporal = Peso[Kg]/(Altura[m])^2)
* No hay valores nulos en el dataframe, se ha encontrado un registro duplicado que deberá eliminarse.
* Para verificar los outliers utilizaremos el método gráfico de la librería matplotlib.

In [55]:
#Verificar outliers (Método gráfico):

### 4-  Data Preparation:

Para esta tapa, primero hacemos una copia del dataset que ajustaremos a nuestras necesidades segun las observaciones mencionadas anteriormente.

In [56]:
#Copia del dataset:
df_copy = df.copy()

In [57]:
#Eliminar valor duplicado:

#Creo una variable que me indique si hay valores duplicados:
duplicados = df_copy.duplicated()
#Muestro los valores duplicados:
fila_duplicada = df_copy[duplicados]
print("Fila duplicada:")
print(fila_duplicada)
#Elimino los valores duplicados:
df_copy.drop_duplicates(inplace=True)
#Verifico que se hayan eliminado los valores duplicados:
print(f"Total de valores duplicados: \n{df_copy.duplicated().sum()}\n")

Fila duplicada:
        age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
12473  27.0      F      157.0       49.1        30.7       70.0      86.0

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm class
12473       27.7                     19.7            51.0          167.0     A
Total de valores duplicados:
0

In [58]:
# Conversión cm a m.
#Conversion y renombrado de la altura (height_cm):
df_copy["alto_m"] = df_copy["height_cm"]/100
#Conversion y renombrado de columna Sentarse e inclinarse hacia adelante (sit and bend forward_cm):
df_copy["sentarse_inclinarse_m"] = df_copy["sit and bend forward_cm"]/100
#Conversion y renombrado de columna salto en largo (broad jump_cm):
df_copy["salto_largo_m_"] = df_copy["broad jump_cm"]/100

#Eliminar columnas en cm.
df_copy.drop(["height_cm","sit and bend forward_cm","broad jump_cm"], axis=1, inplace=True)



df_copy.head()

,age,gender,weight_kg,body fat_%,diastolic,systolic,gripForce,sit-ups counts,class,alto_m,sentarse_inclinarse_m,salto_largo_m_
0,27.0,M,75.24,21.3,80.0,130.0,54.9,60.0,C,1.723,0.184,2.17
1,25.0,M,55.80,15.7,77.0,126.0,36.4,53.0,A,1.650,0.163,2.29
2,31.0,M,78.00,20.1,92.0,152.0,44.8,49.0,C,1.796,0.120,1.81
3,32.0,M,71.10,18.4,76.0,147.0,41.4,53.0,B,1.745,0.152,2.19
4,28.0,M,67.70,17.1,70.0,127.0,43.5,45.0,B,1.738,0.271,2.17