# PRACTICA PROFESIONALIZANTE I

## Proyecto: Predicción de grasa corporal

### Docentes: 
* Pérez, Narciso
* Prado, Héctor
* Charletti, Carlos

### Alumnos:
* Ingaramo, Ma. Eugenia - Sala 1
* Lonardi, Pablo - Sala  1
* Margheim, Carolina - Sala 2
* Ontiveros, Manuel -  Sala 1
* Sosa, Rorigo - Sala 2
* Zenere, Mauricio - Sala 2

### Sobre Nosotros:
Somos una innovadora startup dedicada a resolver desafíos complejos de diferentes empresas u organizaciones utilizando para tal fin diferentes herramientas de ciencia de datos. Utilizamos diferentes herramientas de analisis, exploración, visualizacion y predicción de datos.

### Situación:

Un consorcio formado por reconocidos médicos especializados en medicina deportiva, entrenadores personales y nutricionistas de élite nos ha contratado para abordar una problemática crítica Observan una creciente interconexión entre el rendimiento físico y la salud de los deportistas, pero carecen de una herramienta precisa que les permita prever y optimizar ambos aspectos en sus atletas.

### Solución propuesta:

Nuestro objetivo es desarrollar una plataforma innovadora que integre datos clave sobre la salud y el rendimiento físico. Esta plataforma proporcionará predicciones precisas y recomendaciones fundamentadas en datos. Buscamos empoderar a los profesionales del deporte para que tomen decisiones informadas que impulsen el rendimiento y mejoren la salud de los deportistas. Esta colaboración representa un desafío apasionante donde combinaremos nuestro expertise en ciencia de datos con el conocimiento experto de los médicos y entrenadores. Juntos, vamos a revolucionar la forma en que se abordan la salud y el rendimiento en el ámbito deportivo, marcando un hito significativo en la industria.

### Trabajo en el Notebook:
* **Análisis Exploratorio de Datos (EDA):**

Realizaremos un análisis exploratorio de datos exhaustivo. Exploraremos cómo la edad, el género, la altura, el peso y otros factores influyen en el rendimiento físico y la salud de las personas. Este análisis nos ayudará a comprender las relaciones clave entre las variables y nos guiará en la construcción de modelos precisos.

* **Modelado de Machine Learning:**
Utilizaremos avanzadas técnicas de aprendizaje automático para crear un modelo preciso de predicción. Entrenaremos el modelo con el conjunto de datos y evaluaremos su rendimiento. Nuestro objetivo es lograr un modelo que prediga el rendimiento físico y la salud con alta precisión.

### Trabajo en Streamlit:
* **Desarrollo de la Aplicación Web:**
Construiremos una aplicación web interactiva utilizando Streamlit. Esta aplicación permitirá a los profesionales de la salud y los deportistas ingresar información sobre sus pacientes, como edad, género, altura, peso, entre otros. Basándonos en los datos ingresados, nuestro modelo proporcionará predicciones sobre el rendimiento físico y la salud.

* **Facilitando Decisiones Informadas:**
La aplicación proporcionará información y recomendaciones fundamentadas en datos. Esto permitirá a los usuarios tomar decisiones informadas sobre la mejora de la salud y el rendimiento físico de sus pacientes o de ellos mismos. Además, podrán evaluar estrategias para optimizar el rendimiento físico basadas en los resultados de nuestro modelo.

### Modelado:

Una vez obtenido el acceso a la base, se volcó el contenido de la misma a un archivo .csv. El consorcio nos brindó una descripción de las variables presentes en el mismo, como así también el dominio o rango esperado de sus variables numéricas, en caso de que haya algún tipo de error en la base de datos. En una primera etapa se le prestará se le prestará especial atención a aquellas variables que contengan valores considerados absurdos e imposibles para el ser humano.

### Descripción  de variables:

Contexto: El dataset contiene 13.393 registros que ilustran el grado de rendimiento con la edad y algunos datos de performance en el ejercicio distribuidos en las siguientes 12 columnas.

* age (Edad = años): 20 - 64
* gender (Género = Masculino/Femenino): F,M
* height_cm (Altura en centímetros): cm
* weight_kg (Peso en kilogramos)
* body fat_% (Porcentaje de grasa corporal)
* diastolic (Presión arterial diastólica - min)
* systolic (Presión arterial sistólica - min)
* gripForce (Fuerza de agarre)
* sit and bend forward_cm (Sentarse e inclinarse hacia adelante): cm
* sit-ups counts (Cantidad de abdominales)
* broad jump_cm (Salto largo): cm
* class : A,B,C,D ( A: Mejor - D: Peor) / Variable categórica ordinal

### 1-  Dependencies:

In [191]:
### Importar librerías:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

### 2-  Data Acquisition:

In [192]:
# Importar dataset  desde github (raw):
url="https://raw.githubusercontent.com/CaroMargh/Grupo1-PP1/main/data/bodyPerformance.csv"
# Leer dataset:
df = pd.read_csv(url)
# Mostrar dataset:
display(df)

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27.0,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25.0,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31.0,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32.0,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28.0,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
13388,25.0,M,172.1,71.80,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21.0,M,179.7,63.90,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39.0,M,177.2,80.50,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64.0,F,146.1,57.70,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34.0,M,164.0,66.10,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

### 3-  Data Understanding:

In [193]:
# Descripción del dataset:

def description (data: pd.DataFrame):
    print(f"Shape: \n{data.shape}\n")
    print(f"Dimension: \n{data.ndim}\n")
    print(f"Data types: \n{data.dtypes}\n")
    print(f"Data information: \n{data.info()}\n")
    print(f"Data description: \n{data.describe()}\n")
    print(f"Total de valores nulos: \n{data.isnull().sum()}\n")
    print(f"Total de valores duplicados: \n{data.duplicated().sum()}\n")

description(df)

Shape:
(13393, 12)

Dimension:
2

Data types:
age                        float64
gender                      object
height_cm                  float64
weight_kg                  float64
body fat_%                 float64
diastolic                  float64
systolic                   float64
gripForce                  float64
sit and bend forward_cm    float64
sit-ups counts             float64
broad jump_cm              float64
class                       object
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      13393 non-null  float64
 1   gender                   13393 non-null  object
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13393 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13393 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object
dtypes: float64(10), object(2)
memory usage: 1.2+ MB
Data information:
None

Data description:
                age     height_cm     weight_kg    body fat_%     diastolic  \
count  13393.000000  13393.000000  13393.000000  13393.000000  13393.000000
mean      36.775106    168.559807     67.447316     23.240165     78.796842
std       13.625639      8.426583     11.949666      7.256844     10.742033
min       21.000000    125.000000     26.300000      3.000000      0.000000
25%       25.000000    162.400000     58.200000     18.000000     71.000000
50%       32.000000    169.200000     67.400000     22.800000     79.000000
75%       48.000000    174.800000     75.300000     28.000000     86.000000
max       64.000000    193.800000    138.100000     78.400000    156.200000

           systolic     gripForce  sit and bend forward_cm  sit-ups counts  \
count  13393.000000  13393.000000             13393.000000    13393.000000
mean     130.234817     36.963877                15.209268       39.771224
std       14.713954     10.624864                 8.456677       14.276698
min        0.000000      0.000000               -25.000000        0.000000
25%      120.000000     27.500000                10.900000       30.000000
50%      130.000000     37.900000                16.200000       41.000000
75%      141.000000     45.200000                20.700000       50.000000
max      201.000000     70.500000               213.000000       80.000000

       broad jump_cm
count   13393.000000
mean      190.129627
std        39.868000
min         0.000000
25%       162.000000
50%       193.000000
75%       221.000000
max       303.000000

Total de valores nulos:
age                        0
gender                     0
height_cm                  0
weight_kg                  0
body fat_%                 0
diastolic                  0
systolic                   0
gripForce                  0
sit and bend forward_cm    0
sit-ups counts             0
broad jump_cm              0
class                      0
dtype: int64

Total de valores duplicados:
1

#### Observaciones:

* Se podrían realizar la conversión de altura de cm a m.
* La columna de genero y la de clase se convertirán a formato de datos categóricos usando get_dummies.
* Sería util pasar las columnas en centímetros a metros para unificar criterios y luego borrar las columnas en cm.
* Es útil cambiar el nombre de las columnas para el entendimiento de todo el equipo que habla español
* Con los valores otorgados se podría calcular el IMC (Índice de Masa Corporal = Peso[Kg]/(Altura[m])^2)
* No hay valores nulos en el dataframe, se ha encontrado un registro duplicado que deberá eliminarse.
* Para verificar los outliers utilizaremos el método gráfico de la librería matplotlib.

In [194]:
#Verificar outliers (Método gráfico):

### 4-  Data Preparation:

Para esta tapa, primero hacemos una copia del dataset que ajustaremos a nuestras necesidades segun las observaciones mencionadas anteriormente.

In [195]:
#Copia del dataset:
df_copy = df.copy()

In [196]:
#Eliminar valor duplicado:

#Creo una variable que me indique si hay valores duplicados:
duplicados = df_copy.duplicated()
#Muestro los valores duplicados:
fila_duplicada = df_copy[duplicados]
print("Fila duplicada:")
print(fila_duplicada)
#Elimino los valores duplicados:
df_copy.drop_duplicates(inplace=True)
#Verifico que se hayan eliminado los valores duplicados:
print(f"Total de valores duplicados: \n{df_copy.duplicated().sum()}\n")

Fila duplicada:
        age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
12473  27.0      F      157.0       49.1        30.7       70.0      86.0

       gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm class
12473       27.7                     19.7            51.0          167.0     A
Total de valores duplicados:
0

In [197]:
# Conversión cm a m.
#Conversion y renombrado de la altura (height_cm):
df_copy["alto_m"] = df_copy["height_cm"]/100
#Conversion y renombrado de columna Sentarse e inclinarse hacia adelante (sit and bend forward_cm):
df_copy["sentarse_inclinarse_m"] = df_copy["sit and bend forward_cm"]/100
#Conversion y renombrado de columna salto en largo (broad jump_cm):
df_copy["salto_largo_m_"] = df_copy["broad jump_cm"]/100

#Eliminar columnas en cm.
df_copy.drop(["height_cm","sit and bend forward_cm","broad jump_cm"], axis=1, inplace=True)

# Calcula el IMC:
df_copy['IMC'] = df_copy['weight_kg'] / (df_copy['alto_m'] ** 2)

#Renombrar las columnas:
df_copy.rename(columns={"age": "edad", "gender": "genero", "weight_kg": "peso_kg","body fat_%": "grasa_corporal_%","diastolic": "diastolica","systolic": "sistolica","gripForce": "fuerza_agarre",
"sit-ups counts": "cant_abdominales","class": "clase"}, inplace=True)

df_copy.head(100)

,edad,genero,peso_kg,grasa_corporal_%,diastolica,sistolica,fuerza_agarre,cant_abdominales,clase,alto_m,sentarse_inclinarse_m,salto_largo_m_,IMC
0,27.0,M,75.24,21.3,80.0,130.0,54.9,60.0,C,1.723,0.184,2.17,25.344179
1,25.0,M,55.80,15.7,77.0,126.0,36.4,53.0,A,1.650,0.163,2.29,20.495868
2,31.0,M,78.00,20.1,92.0,152.0,44.8,49.0,C,1.796,0.120,1.81,24.181428
3,32.0,M,71.10,18.4,76.0,147.0,41.4,53.0,B,1.745,0.152,2.19,23.349562
4,28.0,M,67.70,17.1,70.0,127.0,43.5,45.0,B,1.738,0.271,2.17,22.412439
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,41.0,M,65.70,21.5,90.0,151.0,49.6,54.0,A,1.667,0.187,2.42,23.642542
96,50.0,F,57.20,32.0,69.0,134.0,21.1,17.0,C,1.584,0.186,1.36,22.797419
97,22.0,M,72.00,30.4,75.0,115.0,34.6,54.0,C,1.758,0.190,1.88,23.296719
98,56.0,M,70.90,19.5,83.0,135.0,47.9,44.0,B,1.730,0.111,1.62,23.689398
99,46.0,F,52.20,27.2,84.0,127.0,22.9,30.0,D,1.591,0.179,1.36,20.621970

* Insight: Observamos que los datos de grasa corporal y el calculo del IMC son diferentes.

In [198]:
df_copy.describe(include= "object").T

        count unique top  freq
genero  13392      2   M  8467
clase   13392      4   C  3349

Preparamos los datos de las 12 columnas para realizar la predicción de la clase a la que pertenece un paciente (Variable dependiente o target: "clase") en base los datos ingresados. De las variables independientes (11 columnas restantes) podemos decir que solo una (genero), es una variable categórica. Procederemos a convertirla en una variable numérica donde M:1, F. Misma situación con la variable independiente (A:1, B:2, C:3 y D:4)

* Insight: Observamos que la cantidad de masculinos en el dataset es casi el doble de la población femenina.
* Insight: La cantidad de pacientes clase A es la misma que B, y la cantidad de pacientes tipo C es la misma que D.

In [199]:
#Binarizado de la columna genero: Utilizamos get_dummies para crear una columna por cada valor de la columna genero. (La columna genero se elimina y se crea genero_M donde M:1 / F:0)

df_copy = pd.get_dummies(df_copy, columns=['genero'], drop_first=True)
# renombramos la columna genero_M a genero:
df_copy.rename(columns={"genero_M":'genero'},inplace=True)
conteo_genero = df_copy['genero'].value_counts()

# Mostrar los conteos de las columnas genero y clase:
print('Cantidad de 0 y 1 en la columna género:')
print(conteo_genero)

Cantidad de 0 y 1 en la columna género:
1    8467
0    4925
Name: genero, dtype: int64

In [200]:
# Asignamos valores numéricos a las clases: Usamos la función labelEncoder para mapear los valores categóricos de "clase" a valores numericos.

# Mapeo de valores de la columna clase:
# A:0,
# B:1,
# C:2,
# D:3

encode =LabelEncoder()
df_copy["clase_encode"] = encode.fit_transform(df_copy["clase"])
# Eliminamos la columna clase:
df_copy.drop(["clase"], axis=1, inplace=True)
# renombramos la columna clase_encode a clase:
df_copy.rename(columns={"clase_encode":'clase'},inplace=True)
conteo_clase = df_copy['clase'].value_counts()
print('Cantidad de 0,1,2,3 en la columna clase:')
print(conteo_clase)

Cantidad de 0,1,2,3 en la columna clase:
2    3349
3    3349
0    3347
1    3347
Name: clase, dtype: int64

In [201]:
#Reordenamos:
ordenado =[
'edad',
'genero',
'alto_m', 
'peso_kg', 
'grasa_corporal_%',
'IMC',
'diastolica', 
'sistolica', 
'fuerza_agarre', 
'sentarse_inclinarse_m',
'cant_abdominales', 
'salto_largo_m_',
'clase',
]
df_copy = df_copy[ordenado]

# Mostrar dataset:
df_copy.head(100)

,edad,genero,alto_m,peso_kg,grasa_corporal_%,IMC,diastolica,sistolica,fuerza_agarre,sentarse_inclinarse_m,cant_abdominales,salto_largo_m_,clase
0,27.0,1,1.723,75.24,21.3,25.344179,80.0,130.0,54.9,0.184,60.0,2.17,2
1,25.0,1,1.650,55.80,15.7,20.495868,77.0,126.0,36.4,0.163,53.0,2.29,0
2,31.0,1,1.796,78.00,20.1,24.181428,92.0,152.0,44.8,0.120,49.0,1.81,2
3,32.0,1,1.745,71.10,18.4,23.349562,76.0,147.0,41.4,0.152,53.0,2.19,1
4,28.0,1,1.738,67.70,17.1,22.412439,70.0,127.0,43.5,0.271,45.0,2.17,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,41.0,1,1.667,65.70,21.5,23.642542,90.0,151.0,49.6,0.187,54.0,2.42,0
96,50.0,0,1.584,57.20,32.0,22.797419,69.0,134.0,21.1,0.186,17.0,1.36,2
97,22.0,1,1.758,72.00,30.4,23.296719,75.0,115.0,34.6,0.190,54.0,1.88,2
98,56.0,1,1.730,70.90,19.5,23.689398,83.0,135.0,47.9,0.111,44.0,1.62,1
99,46.0,0,1.591,52.20,27.2,20.621970,84.0,127.0,22.9,0.179,30.0,1.36,3

### 5- Data Visualization:

### 6-  Train Model:

Para este problema de clasificación multiclase utilizaremos algoritmos de regresión logística:

#### Escalado de las variables numericas continuas (Estandarización):

In [202]:
# Selecciono las columnas con valores numéricos continuos:
columnas_a_escalar = [
'edad',
'alto_m', 
'peso_kg', 
'grasa_corporal_%',
'IMC',
'diastolica', 
'sistolica', 
'fuerza_agarre', 
'sentarse_inclinarse_m',
'cant_abdominales', 
'salto_largo_m_',
]

# Creo un nuevo dataframe con las columnas a escalar:
df_columnas_escalar = df_copy[columnas_a_escalar]

# Instancio el objeto StandardScaler:
scaler = StandardScaler()

# Escalo las columnas seleccionadas
df_scaled_values = scaler.fit_transform(df_columnas_escalar)

# Crear un nuevo DataFrame escalado
df_scaled = pd.DataFrame(df_scaled_values, columns=columnas_a_escalar)

## ERROR A CORREGIR:

Hay que verificar este error, df_copy y df_scaled no contienen datos nulos. Al momento de volver a agregar las columnas "genero" y "clase" a df_scaled se agregan dos valores nulos en esas columnas. No se por que esta pasando eso. Lo soluciné eliminando las filas con nulos pero no es lo ideal supongo.

In [203]:
# Verifico nulos en 'genero' y 'clase' en df_copy
print('Nulos en genero en df_copy:', df_copy['genero'].isnull().sum())
print('Nulos en clase en df_copy:', df_copy['clase'].isnull().sum())

# Agregar 'genero' y 'clase' a df_scaled
df_scaled['genero'] = df_copy['genero']
df_scaled['clase'] = df_copy['clase']

# Verificar y eliminar filas con nulos en 'genero' y 'clase'
df_scaled.dropna(subset=['genero', 'clase'], inplace=True)

# Verifico nulos en df_scaled
print('Nulos en df_scaled:', df_scaled.isnull().sum())

Nulos en genero en df_copy: 0
Nulos en clase en df_copy: 0
Nulos en df_scaled: edad                     0
alto_m                   0
peso_kg                  0
grasa_corporal_%         0
IMC                      0
diastolica               0
sistolica                0
fuerza_agarre            0
sentarse_inclinarse_m    0
cant_abdominales         0
salto_largo_m_           0
genero                   0
clase                    0
dtype: int64

In [204]:
#Reordenamos:
ordenado =[
'edad',
'genero',
'alto_m', 
'peso_kg', 
'grasa_corporal_%',
'IMC',
'diastolica', 
'sistolica', 
'fuerza_agarre', 
'sentarse_inclinarse_m',
'cant_abdominales', 
'salto_largo_m_',
'clase',
]
df_scaled = df_scaled[ordenado]

#Mostrar dataset escalado:
df_scaled.head(100)

,edad,genero,alto_m,peso_kg,grasa_corporal_%,IMC,diastolica,sistolica,fuerza_agarre,sentarse_inclinarse_m,cant_abdominales,salto_largo_m_,clase
0,-0.717473,1.0,0.443785,0.652068,-0.267290,0.590966,0.111946,-0.016189,1.688110,0.377347,1.417000,0.673949,2.0
1,-0.864258,1.0,-0.422582,-0.974898,-1.039006,-1.057692,-0.167337,-0.288131,-0.053138,0.129020,0.926679,0.974946,0.0
2,-0.423903,1.0,1.310152,0.883058,-0.432658,0.195574,1.229081,1.479495,0.737483,-0.379460,0.646496,-0.229043,2.0
3,-0.350510,1.0,0.704882,0.305585,-0.666929,-0.087300,-0.260432,1.139567,0.417470,-0.001056,0.926679,0.724115,1.0
4,-0.644080,1.0,0.621806,0.021033,-0.846077,-0.405966,-0.818999,-0.220146,0.615125,1.406131,0.366313,0.673949,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.310022,1.0,-0.220825,-0.146351,-0.239729,0.012328,1.042892,1.411510,1.189266,0.412822,0.996725,1.301026,0.0
96,0.970554,0.0,-1.205873,-0.857730,1.207238,-0.275055,-0.912094,0.255754,-1.493197,0.400997,-1.594970,-1.357782,2.0
97,-1.084435,1.0,0.859167,0.380907,0.986748,-0.105269,-0.353527,-1.035973,-0.222557,0.448297,0.996725,-0.053461,2.0
98,1.410909,1.0,0.526861,0.288846,-0.515342,0.028261,0.391230,0.323740,1.029259,-0.485885,0.296267,-0.705621,1.0
99,0.676984,0.0,-1.122796,-1.276189,0.545767,-1.014811,0.484325,-0.220146,-1.323779,0.318221,-0.684375,-1.357782,3.0

In [205]:
df_copy.head(100)

,edad,genero,alto_m,peso_kg,grasa_corporal_%,IMC,diastolica,sistolica,fuerza_agarre,sentarse_inclinarse_m,cant_abdominales,salto_largo_m_,clase
0,27.0,1,1.723,75.24,21.3,25.344179,80.0,130.0,54.9,0.184,60.0,2.17,2
1,25.0,1,1.650,55.80,15.7,20.495868,77.0,126.0,36.4,0.163,53.0,2.29,0
2,31.0,1,1.796,78.00,20.1,24.181428,92.0,152.0,44.8,0.120,49.0,1.81,2
3,32.0,1,1.745,71.10,18.4,23.349562,76.0,147.0,41.4,0.152,53.0,2.19,1
4,28.0,1,1.738,67.70,17.1,22.412439,70.0,127.0,43.5,0.271,45.0,2.17,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,41.0,1,1.667,65.70,21.5,23.642542,90.0,151.0,49.6,0.187,54.0,2.42,0
96,50.0,0,1.584,57.20,32.0,22.797419,69.0,134.0,21.1,0.186,17.0,1.36,2
97,22.0,1,1.758,72.00,30.4,23.296719,75.0,115.0,34.6,0.190,54.0,1.88,2
98,56.0,1,1.730,70.90,19.5,23.689398,83.0,135.0,47.9,0.111,44.0,1.62,1
99,46.0,0,1.591,52.20,27.2,20.621970,84.0,127.0,22.9,0.179,30.0,1.36,3

#### Entrenamiento del modelo de regresión  logística:

In [206]:
#Separar el dataframe en train y test:
y = df_scaled['clase']
X = df_scaled.drop(['clase'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [207]:
# Creamos el Modelo Logístico:
modelo_logistico = LogisticRegression(max_iter=1000)

#Entrenamos el modelo:
modelo_logistico.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [208]:
#Realizo las pruebas con el test escalado:
y_pred = modelo_logistico.predict(X_test)
y_pred

array([3., 3., 2., ..., 2., 1., 3.])

In [209]:
y_test.values

array([3., 3., 2., ..., 2., 1., 2.])

#### Métricas del modelo:

In [210]:
# Calculamos el porcentaje de aciertos:
print(f"El porcentaje de aciertos es: {accuracy_score(y_test, y_pred)}")
# Calculamos el error cuadrático medio:
ecm = mean_squared_error(y_test, y_pred)
print(f"El error cuadrático medio es: {ecm}")
# Calculamos el R2:
r2 = r2_score(y_test, y_pred)
print(f"El R2 es: {r2}")

El porcentaje de aciertos es: 0.6002239641657335
El error cuadrático medio es: 0.6786114221724524
El R2 es: 0.4665048866985233

#### Creamos una función de predicción de clase usando el modelo entrenado:

In [211]:
def clase_predict(edad, genero, alto_m, peso_kg, grasa_corporal, imc, diastolica, sistolica, fuerza_agarre,
                   sentarse_inclinarse, cant_abdominales, salto_largo):
    # Crear un DataFrame con los valores de las variables independientes
    datos_entrada = pd.DataFrame({
        'edad': [edad],
        'genero': [genero],
        'alto_m': [alto_m],
        'peso_kg': [peso_kg],
        'grasa_corporal_%': [grasa_corporal],
        'IMC': [imc],
        'diastolica': [diastolica],
        'sistolica': [sistolica],
        'fuerza_agarre': [fuerza_agarre],
        'sentarse_inclinarse_m': [sentarse_inclinarse],
        'cant_abdominales': [cant_abdominales],
        'salto_largo_m_': [salto_largo]
        })
    
    # Columnas a escalar (todas excepto 'genero')
    columnas_a_escalar = ['edad', 'alto_m', 'peso_kg', 'grasa_corporal_%', 'IMC', 'diastolica', 
                      'sistolica', 'fuerza_agarre', 'sentarse_inclinarse_m', 'cant_abdominales', 
                      'salto_largo_m_']
    
    # Creo un nuevo DataFrame con las columnas a escalar
    df_columnas_escalar = datos_entrada[columnas_a_escalar]

    # Escalo las columnas seleccionadas
    datos_entrada[columnas_a_escalar] = scaler.fit_transform(df_columnas_escalar)
    
    # Hacer la predicción
    prediccion_clase = modelo_logistico.predict(datos_entrada)

    # return prediccion_clase
    return prediccion_clase[0]

# Prueba de la función:
prediccion = clase_predict(edad=25, genero=1, alto_m=1.65, peso_kg=55.8, grasa_corporal=15.7, imc=20.49, diastolica=77, sistolica=126, fuerza_agarre= 36.4, sentarse_inclinarse=16.3, cant_abdominales=53, salto_largo=229)

print(f"La clase predicha es: {prediccion}")

La clase predicha es: 2.0

#### Prueba de la función de predicción:

In [212]:
# Ejemplo de uso (Segundo valor del dataset)):
# age                         25.0
# gender                         M (1)
# height_cm                  165.0
# weight_kg                   55.8
# body fat_%                  15.7
# IMC                         20.49
# diastolic                   77.0
# systolic                   126.0
# gripForce                   36.4
# sit and bend forward_cm     16.3
# sit-ups counts              53.0
# broad jump_cm              229.0
# class                          A (Deberia predecir 0)

clase_predicha = clase_predict(
    25.0,
    1,
    165.0,
    55.8,
    15.7,
    20.495868,
    77.0,
    126.0,
    36.4,
    16.3,
    53.0,
    229.0
    )
print('Clase predicha:', clase_predicha)

Clase predicha: 2.0

In [213]:
df_scaled.iloc[1]

edad                    -0.864258
genero                   1.000000
alto_m                  -0.422582
peso_kg                 -0.974898
grasa_corporal_%        -1.039006
IMC                     -1.057692
diastolica              -0.167337
sistolica               -0.288131
fuerza_agarre           -0.053138
sentarse_inclinarse_m    0.129020
cant_abdominales         0.926679
salto_largo_m_           0.974946
clase                    0.000000
Name: 1, dtype: float64

In [214]:
df_copy.iloc[1]

edad                      25.000000
genero                     1.000000
alto_m                     1.650000
peso_kg                   55.800000
grasa_corporal_%          15.700000
IMC                       20.495868
diastolica                77.000000
sistolica                126.000000
fuerza_agarre             36.400000
sentarse_inclinarse_m      0.163000
cant_abdominales          53.000000
salto_largo_m_             2.290000
clase                      0.000000
Name: 1, dtype: float64